Repository FRONTENDBOOTCAMP-13th/JS-08-bibim, pull requests merged in 2025-05, with the labels that each got.

#8 📝 docs: Leave a footprint in the README file
  README.md
Labels: documentation

#16 Feature/11-news-page Added commit guideline documentation and implemented & refined the layout and content for the news article and quiz pages.
  .github/ISSUE_TEMPLATE/commit-rule.md
  src/news-page.html
Labels: ✨ styling

#17 🎨 feat: Header and Category
  public/font/pretendardvariable.css
  public/font/woff2/PretendardVariable.woff2
  public/wagle.svg
  src/components/category.html
  src/components/header.html
  src/typescript/category.ts
Labels: 🧰 feature

#18 🎨 feat: Implementing Quiz
  package-lock.json
  package.json
  src/components/quiz.html
  src/typescript/deepseekQuiz.js
Labels: 🧰 feature

#50 🎨 feat: Converted the My Page section into a side menu with features like points, attendance calendar, and favorites.
  src/pages/toggle-menu.html
  src/typescript/toggle-menu.ts
Labels: 🧰 feature, 🎯medium priority, ✨ styling

#51 🎨 feat: Implementing Quiz feature
  src/components/quiz.html
  src/typescript/quiz.ts
Labels: 🧰 feature

#52 🎨 feat: Implementing History Feature and Component
  src/components/history.html
  src/typescript/history.ts
  src/typescript/main-page.ts
Labels: 🧰 feature

#62 🔀 merge: Merge branches Feature/44 landing page add
  index.html
  package-lock.json
  src/main.ts
  src/pages/landingPage.html
  src/pages/svg/Asiae_CI_Light.svg
  src/pages/svg/Dong-a_Ilbo_logo.svg
  src/pages/svg/Hankyorehe.svg
  src/pages/svg/Hankyung_logo.svg
  src/pages/svg/Seoul_Shinmun_logo.svg
  src/pages/svg/The_JoongAng_logo.svg
  src/pages/svg/The_kyunghyang_shinmun_logo.svg
  src/pages/svg/YTN_2014_logo.svg
  src/style.css
  src/types/swiper-css.d.ts
  src/typescript/landingPage.ts
  src/typescript/naverapi.ts
  tsconfig.json
Labels: 🧰 feature, 🎯 high priority, ✨ styling, 🏷️refactor

#73 🎨 feat: Fixed dev errors, updated script setup, modified toggle menu structure, and temporarily disabled DeepSeek quiz logic via GPT.
  src/pages/quiz.html
  src/pages/toggle-menu.html
  src/pages/webp/503error.webp
  src/typescript/quiz.ts
  src/typescript/updatePoint.ts
Labels: 🧰 feature, 🎯medium priority, ✨ styling, 🏷️refactor

#80 🩹 modify: Final update to main page header
  src/pages/main-page.html
Labels: ✨ styling

#79 🐛 bugfix: Fix Quiz Page Bug
  src/pages/quiz.html
  src/typescript/main-page.ts
  src/typescript/quiz.ts
Labels: 🐛 bugfix

#91 💄 style: Update main page header and toggle menu UI
  src/pages/main-page.html
  src/typescript/toggle-menu.ts
Labels: ✨ styling

#101 🎨 feat: Add toggle menu tab functionality
  src/pages/main-page.html
  src/typescript/toggle-menu.ts
Labels: 🧰 feature, 🎯critical

#104 ♻️ refactor: separate toggle menu logic
  src/pages/main-page.html
  src/typescript/toggle-menu.ts
Labels: 🎯critical, 🏷️refactor

#134 ♻️ refactor: Delete My Page, unified layout titles
  index.html
  src/pages/game/baseball-game.html
  src/pages/game/game-page.html
  src/pages/game/question-game.html
  src/pages/game/soccer-game.html
  src/pages/main-page.html
  src/pages/my-page.html
  src/pages/quiz.html
Labels: 🎯low priority, ✨ styling, 🏷️refactor

#135 💄 style: game style development
  src/pages/game/baseball-game.html
  src/pages/game/game-page.html
  src/pages/game/question-game.html
  src/pages/game/soccer-game.html
Labels: ✨ styling, 🏷️refactor
